# Pandas

In [1]:
import pandas as pd

In [6]:
#reading csv
f = pd.read_csv('myFile.csv', sep=";")

In [7]:
f

    Name  Age Student
0  Jonas   21     Yes
1  Maria   18      No
2  Peter   34      No
3  Joana   25     Yes

In [8]:
data = [[1,'Ackley',"Berrien Springs"], [2,'Luci','Rio de Janeiro'],[3, 'Ketlyn','West Palm Beach']]

f = pd.DataFrame(data,columns=['id','name','city'])

In [9]:
f

   id    name             city
0   1  Ackley  Berrien Springs
1   2    Luci   Rio de Janeiro
2   3  Ketlyn  West Palm Beach

In [14]:
f = pd.read_csv("pokemon.csv", sep=',')

In [15]:
f

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

# Selecting and filtering columns

In [23]:
columns = f[['Name','Attack','Defense']]
columns

                      Name  Attack  Defense
0                Bulbasaur      49       49
1                  Ivysaur      62       63
2                 Venusaur      82       83
3    VenusaurMega Venusaur     100      123
4               Charmander      52       43
..                     ...     ...      ...
795                Diancie     100      150
796    DiancieMega Diancie     160      110
797    HoopaHoopa Confined     110       60
798     HoopaHoopa Unbound     160       60
799              Volcanion     110      120

[800 rows x 3 columns]

In [23]:
columns = f[['Name','Attack','Defense']]
columns

                      Name  Attack  Defense
0                Bulbasaur      49       49
1                  Ivysaur      62       63
2                 Venusaur      82       83
3    VenusaurMega Venusaur     100      123
4               Charmander      52       43
..                     ...     ...      ...
795                Diancie     100      150
796    DiancieMega Diancie     160      110
797    HoopaHoopa Confined     110       60
798     HoopaHoopa Unbound     160       60
799              Volcanion     110      120

[800 rows x 3 columns]

In [21]:
columns = f [["Name"]],[["Attack"]],[["Speed"]]
columns

(                      Name
 0                Bulbasaur
 1                  Ivysaur
 2                 Venusaur
 3    VenusaurMega Venusaur
 4               Charmander
 ..                     ...
 795                Diancie
 796    DiancieMega Diancie
 797    HoopaHoopa Confined
 798     HoopaHoopa Unbound
 799              Volcanion

 [800 rows x 1 columns],
 [['Attack']],
 [['Speed']])

In [22]:
lines = f[f['Attack']>100]
lines

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
39,34,Nidoking,Poison,Ground,505,81,102,77,85,75,85,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

# Creating a new column

In [25]:
f["Strength"] = f ["Attack"] + f ["Defense"] + f ["Speed"]
f

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Strength
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,143
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,185
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,245
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,303
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,300
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,380
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,240
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,300
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,300

In [26]:
f["Power_Attack"] = f["Attack"]**2

In [27]:
f.rename(columns = {'Attack': 'Aggression'}, inplace=True)

In [30]:
f.drop(columns=['Power_Attack', "Strength"], inplace = True)
f

,#,Name,Type 1,Type 2,Total,HP,Aggression,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [31]:
f = pd.DataFrame({
    'A':[10,20,30,40],
    'B':[5,4,8,2],
    'C':[100,200,300,400]
}, index=['L1','L2','L3','L4'])
f

     A  B    C
L1  10  5  100
L2  20  4  200
L3  30  8  300
L4  40  2  400

In [33]:
new_df = f['A']
new_df

L1    10
L2    20
L3    30
L4    40
Name: A, dtype: int64

In [36]:
new_df = f[['A','C']]
new_df

     A    C
L1  10  100
L2  20  200
L3  30  300
L4  40  400

In [40]:
f.iloc[0]

A     10
B      5
C    100
Name: L1, dtype: int64

# DATA CLEANING

In [44]:
F = pd.DataFrame({
    'A': [1,2,None, 4],
    'B':[None,2,2,3],
    'C':['x','x','y','y']
})
F

     A    B  C
0  1.0  NaN  x
1  2.0  2.0  x
2  NaN  2.0  y
3  4.0  3.0  y

In [45]:
F.isnull()

       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False  False

In [46]:
F.dropna()

     A    B  C
1  2.0  2.0  x
3  4.0  3.0  y

In [48]:
F.fillna(0)

     A    B  C
0  1.0  0.0  x
1  2.0  2.0  x
2  0.0  2.0  y
3  4.0  3.0  y

# STATISTICS

In [50]:
df = pd.read_csv('house-prices.csv', sep=',')
df

     Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300  1790         2          2       2    No         East
1       2  114200  2030         4          2       3    No         East
2       3  114800  1740         3          2       1    No         East
3       4   94700  1980         3          2       3    No         East
4       5  119800  2130         3          3       3    No         East
..    ...     ...   ...       ...        ...     ...   ...          ...
123   124  119700  1900         3          3       3   Yes         East
124   125  147900  2160         4          3       3   Yes         East
125   126  113500  2070         2          2       2    No        North
126   127  149900  2020         3          3       1    No         West
127   128  124600  2250         3          3       4    No        North

[128 rows x 8 columns]

In [52]:
mean = df ['Price'].mean()
print(mean)

median = df['Price'].median()
print(median)

mode = df['Neighborhood'].mode()[0]
print(mode)

sum_=df['Price'].sum()
print(sum_)

std = df['Price'].std()
print(std)

130427.34375
125950.0
East
16694700
26868.770370734055

In [53]:
df.describe()

,Home,Price,SqFt,Bedrooms,Bathrooms,Offers
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,130427.343750,2000.937500,3.023438,2.445312,2.578125
std,37.094474,26868.770371,211.572431,0.725951,0.514492,1.069324
min,1.000000,69100.000000,1450.000000,2.000000,2.000000,1.000000
25%,32.750000,111325.000000,1880.000000,3.000000,2.000000,2.000000
50%,64.500000,125950.000000,2000.000000,3.000000,2.000000,3.000000
75%,96.250000,148250.000000,2140.000000,3.000000,3.000000,3.000000
max,128.000000,211200.000000,2590.000000,5.000000,4.000000,6.000000